const $=s=>document.querySelector(s),clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),money=n=>'$'+n.toFixed(2),fmt=n=>n>=1e9?(n/1e9).toFixed(2)+'B':n>=1e6?(n/1e6).toFixed(2)+'M':n>=1e3?(n/1e3).toFixed(1)+'k':Math.floor(n).toLocaleString();
const KEY='the-jam-save-v2';
const projects=[
{id:'recipe',name:'Secret Recipe',desc:'Tune the fruit-to-sugar ratio. +15% production.',cost:15,need:5,eff:1.15},
{id:'squeezer',name:'The Squeezer',desc:'A suspiciously effective machine. +0.6 jars/sec.',cost:35,need:25,rate:.6},
{id:'label',name:'Tiny Labels',desc:'Make each jar collectible. +$0.03 price.',cost:65,need:55,price:.03},
{id:'stand',name:'Sunday Stand',desc:'Demand recovers 2× faster.',cost:110,need:100,mult:2},
{id:'kitchen',name:'Second Kitchen',desc:'A second room. +3 jars/sec and more storage.',cost:300,need:200,rate:3,cap:25},
{id:'orchard',name:'Orbital Orchard',desc:'Why grow berries on Earth? +8 jars/sec.',cost:800,need:500,rate:8,cap:40},
{id:'brand',name:'Cult Following',desc:'Fans pay for the feeling. +$0.12 price.',cost:2500,need:1500,price:.12,mult:1.2},
{id:'jamAI',name:'JAM·AI',desc:'It has one job. +25 jars/sec.',cost:9000,need:5000,rate:25,cap:100},
{id:'quantum',name:'Quantum Toast',desc:'The jam is everywhere until observed. +100 jars/sec.',cost:45000,need:25000,rate:100,cap:250},
{id:'moon',name:'Moon Pantry',desc:'Low gravity, high margins. +400 jars/sec.',cost:250000,need:150000,rate:400,cap:1000}];
const achievements=[['first','First Spread',1],['dozen','A Dozen',12],['hundred','Small Business',100],['thousand','Local Legend',1000],['million','Jamillionaire',1e6],['hoarder','Jar Hoarder',100],['premium','Fancy Jar',.5],['cosmic','Cosmic Spread',1e6]];
let s={jars:0,total:0,berries:18,jarsStock:8,funds:8,spark:0,price:.12,demand:1,eff:1,mult:1,auto:0,capacity:12,priceBonus:0,purchased:{},ach:{},logs:[],last:Date.now(),level:1,xp:0,prestige:0,prestigeBonus:1,contract:null,contractProgress:0,contractTimer:0,stirs:0,sold:0,events:0};
try{Object.assign(s,JSON.parse(localStorage.getItem(KEY)||'{}'))}catch(e){}
const xpFor=l=>Math.floor(50*Math.pow(l,1.55));
function save(){s.last=Date.now();localStorage.setItem(KEY,JSON.stringify(s))}
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>x.classList.remove('show'),1800)}
function log(t,good=false){s.logs.unshift({t,good});s.logs=s.logs.slice(0,9);renderLog()}
function xp(n){s.xp+=n;while(s.xp>=xpFor(s.level)){s.xp-=xpFor(s.level);s.level++;s.spark+=s.level*3;log(`Level up: <b>Kitchen ${s.level}</b>.`,true);toast('Kitchen level '+s.level)}}
function phase(){return s.total>=1e6?['COSMIC','Everything is spread.']:s.total>=25000?['GLOBAL','The world has developed a taste.']:s.total>=1500?['CITY','Your jars are becoming an institution.']:['KITCHEN','A tiny kitchen. An enormous destiny.']}
function buy(p){if(s.purchased[p.id]||s.funds<p.cost||s.total<p.need)return;s.funds-=p.cost;s.purchased[p.id]=1;s.auto+=p.rate||0;s.capacity+=p.cap||0;s.eff*=p.eff||1;s.priceBonus+=p.price||0;s.mult*=p.mult||1;s.spark+=Math.ceil(p.cost/20);xp(Math.ceil(p.cost/2));log(`Built <b>${p.name}</b>. The kitchen gets stranger.`,true);toast(p.name+' built');render();save()}
function make(q=1){if(s.berries<q||s.jarsStock<q){toast('Need berries and empty jars.');return}const sale=Math.max(.01,s.price+s.priceBonus)*s.demand*s.prestigeBonus*q;s.berries-=q;s.jarsStock-=q;s.jars+=q;s.total+=q;s.funds+=sale;s.spark+=q;s.demand=clamp(s.demand-.012*q,0,1);s.stirs+=q;xp(q*2);achievementsCheck();render();save()}
function sell(){if(s.jars<1){toast('No jars ready to sell.');return}const q=Math.max(1,Math.floor(s.jars*.15)),sale=q*(s.price+s.priceBonus)*s.demand*s.prestigeBonus;s.jars-=q;s.funds+=sale;s.demand=clamp(s.demand-.025,0,1);s.sold+=q;xp(q*.5);log(`Wholesale buyer took <b>${fmt(q)} jars</b> for ${money(sale)}.`,true);render();save()}
function event(){const e=[['Berry Boom','berries'],['Influencer','demand'],['Sticky Spill','slow'],['Food Critic','cash']][Math.floor(Math.random()*4)];s.events++;if(e[1]==='berries')s.berries=Math.min(s.capacity*2,s.berries+s.capacity);if(e[1]==='demand')s.demand=1;if(e[1]==='slow')s.auto*=.75;if(e[1]==='cash')s.funds+=Math.max(1,s.funds*.12);log(`EVENT — <b>${e[0]}</b>. The market reacts.`,true);toast(e[0])}
function newContract(){const q=[25,75,200,600,1800,6000][Math.min(5,Math.floor(s.level/2))];s.contract={target:q,reward:q*.05+10};s.contractProgress=0;s.contractTimer=45+q/30}
function contractTick(dt){if(!s.contract)newContract();s.contractProgress=clamp(s.contractProgress+s.auto*s.eff*dt,0,s.contract.target);s.contractTimer-=dt;if(s.contractTimer<=0){if(s.contractProgress>=s.contract.target){s.funds+=s.contract.reward;s.spark+=10;log(`CONTRACT COMPLETE — +${money(s.contract.reward)}.`,true);toast('Contract complete!')}else log('Contract expired. Another buyer is coming.');newContract()}}
function achievementsCheck(){for(const a of achievements){if(s.ach[a[0]])continue;let ok=a[0]==='premium'?s.price+s.priceBonus>=.5:a[0]==='hoarder'?s.jars>=100:a[0]==='cosmic'?s.total>=1e6:s.total>=a[2];if(ok){s.ach[a[0]]=1;s.spark+=20;xp(25);log(`ACHIEVEMENT — <b>${a[1]}</b>. +20 ✦`,true);toast(a[1])}}}
function tick(dt){const made=Math.min(s.auto*s.eff*dt,s.berries,s.jarsStock);if(made>0){s.berries-=made;s.jarsStock-=made;s.jars+=made;s.total+=made;s.funds+=made*(s.price+s.priceBonus)*s.demand*s.prestigeBonus;s.demand=clamp(s.demand+dt*.001*s.mult,0,1);xp(made*.15)}s.berries=clamp(s.berries+dt*(.24+s.level*.025)*s.mult,0,s.capacity*2);s.jarsStock=clamp(s.jarsStock+dt*(.11+s.level*.01)*s.mult,0,s.capacity);s.demand=clamp(s.demand+dt*.006*s.mult,0,1);contractTick(dt);if(Math.random()<dt*.012)event();achievementsCheck()}
function prestige(){if(s.total<100000){toast('100,000 total jars required.');return}if(!confirm('Start a new batch? Spark stays and your permanent sales bonus grows.'))return;const p=s.prestige+1,sp=s.spark+p*50;localStorage.removeItem(KEY);s={jars:0,total:0,berries:18,jarsStock:8,funds:8,spark:sp,price:.12,demand:1,eff:1,mult:1,auto:0,capacity:12,priceBonus:0,purchased:{},ach:s.ach,last:Date.now(),level:1,xp:0,prestige:p,prestigeBonus:1+p*.12,contract:null,contractProgress:0,contractTimer:0,stirs:0,sold:0,events:0};log(`NEW BATCH — Prestige ${p}. Sales are now <b>${s.prestigeBonus.toFixed(2)}×</b>.`,true);save();render()}
function renderProjects(){const ready=projects.filter(p=>!s.purchased[p.id]&&s.funds>=p.cost&&s.total>=p.need).length;$('#projects').innerHTML=projects.map(p=>{const own=s.purchased[p.id],locked=s.total<p.need;return `<article class="project ${locked&&!own?'locked':''} ${own?'owned':''}"><div><div class="project-meta"><span>${own?'BUILT':locked?'LOCKED':'READY'}</span><small>${fmt(p.need)} total jars</small></div><h3>${own?'✓ ':''}${p.name}</h3><p>${p.desc}</p></div><button class="buy" ${own||locked||s.funds<p.cost?'disabled':''} data-id="${p.id}">${own?'BUILT':'BUILD'}<span class="cost">${own?'':money(p.cost)}</span></button></article>`}).join('');document.querySelectorAll('.buy').forEach(b=>b.onclick=()=>buy(projects.find(p=>p.id===b.dataset.id)));$('#unlockHint').textContent=ready?ready+' ideas ready':`next at ${fmt(projects.find(p=>!s.purchased[p.id])?.need||100000)} jars`}
function renderLog(){$('#logLines').innerHTML=s.logs.map(x=>`<div class="log-line"><span>${x.good?'✦':'·'}</span>${x.t}</div>`).join('')||'<div class="log-line">· The journal is blank. Start stirring.</div>';$('#logCount').textContent=s.logs.length+' entries'}
function render(){const [ph,fl]=phase();$('#phaseName').textContent=ph;$('#flavor').textContent=fl;$('#jars').textContent=fmt(s.jars);$('#rate').textContent=(s.auto*s.eff).toFixed(1);$('#berries').textContent=Math.floor(s.berries);$('#jarStock').textContent=Math.floor(s.jarsStock);$('#funds').textContent=money(s.funds);$('#spark').textContent=fmt(s.spark);$('#demand').textContent=Math.round(s.demand*100)+'%';$('#statDemand').textContent=Math.round(s.demand*100)+'%';$('#efficiency').textContent=s.eff.toFixed(2)+'×';$('#price').textContent=money(s.price+s.priceBonus);$('#priceRange').value=Math.round(s.price*100);$('#demandBar').style.width=s.demand*100+'%';$('#capacity').textContent=Math.floor(s.capacity);$('#total').textContent=fmt(s.total);$('#level').textContent=s.level;$('#xp').textContent=Math.floor(s.xp)+' / '+xpFor(s.level);$('#xpBar').style.width=s.xp/xpFor(s.level)*100+'%';$('#prestige').textContent=s.prestige;$('#prestigeBonus').textContent=s.prestigeBonus.toFixed(2)+'×';$('#market').textContent=ph;$('#statStatus').textContent=s.auto?'Machines humming':'Hands on deck';const n=projects.find(p=>!s.purchased[p.id]);$('#milestoneTitle').textContent=n?n.name:'The Infinite Jar';$('#milestoneText').textContent=n?n.desc:'You made it. Keep going anyway.';$('#milestoneBar').style.width=n?clamp(s.total/n.need*100,0,100)+'%':'100%';$('#contractProgress').textContent=s.contract?fmt(s.contractProgress)+' / '+fmt(s.contract.target):'—';$('#contractBar').style.width=s.contract?clamp(s.contractProgress/s.contract.target*100,0,100)+'%':'0%';$('#contractReward').textContent=s.contract?money(s.contract.reward):'—';$('#achCount').textContent=Object.keys(s.ach).length+' / '+achievements.length;renderProjects();renderLog()}
$('#jamBtn').onclick=()=>make();$('#sellBtn').onclick=sell;$('#prestigeBtn').onclick=prestige;$('#priceRange').oninput=e=>{s.price=e.target.value/100;render()};$('#priceRange').onchange=()=>{log('Adjusted the jar price. The market noticed.');save()};$('#resetBtn').onclick=()=>{if(confirm('Reset The Jam completely?')){localStorage.removeItem(KEY);location.reload()}};
if(!s.contract)newContract();const away=Math.max(0,(Date.now()-s.last)/1000);if(away>20){const before=s.total;tick(Math.min(3600,away));log(`While you were away, the kitchen made <b>${fmt(s.total-before)} jars</b>.`,true);toast('Welcome back — '+fmt(s.total-before)+' jars made')}setInterval(()=>{const now=Date.now(),dt=Math.min(2,(now-s.last)/1000);s.last=now;tick(dt);render();save()},250);render();if(!s.logs.length)log('Welcome to The Jam. Your first jar is waiting.')